BakeryManagement/Controllers/CategoriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Domain;
using Repository;
using FireSharp.Interfaces;
using FireSharp.Config;
using FireSharp.Response;

namespace BakeryManagement.Controllers
{
    public class CategoriaController : Controller
    {
        private readonly CategoriaDAO _categoriaDAO;

        public CategoriaController(CategoriaDAO categoriaDAO)
        {
            _categoriaDAO = categoriaDAO;
        }

        // GET: Categoria
        public IActionResult Index()
        {
            return View(_categoriaDAO.ListarTodos().ToList());
        }

        // GET: Categoria/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                if (await _categoriaDAO.Create(categoria))
                {
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError("", "A categoria já existe");
            }
            return View();
        }

        public IActionResult Edit(int id)
        {
            Categoria categoria = _categoriaDAO.BuscarPorId(id);

            return View(categoria);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Categoria c)
        {
            _categoriaDAO.Edit(c);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            _categoriaDAO.Remover(id);

            return RedirectToAction("Index");
        }
    }
}

BakeryManagement/Controllers/FornecedorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Domain;
using Repository;
using FireSharp.Interfaces;
using FireSharp.Config;
using FireSharp.Response;

namespace BakeryManagement.Controllers
{
    public class FornecedorController : Controller
    {
        private readonly FornecedorDAO _fornecedorDAO;

        public FornecedorController(FornecedorDAO fornecedorDAO)
        {
            _fornecedorDAO = fornecedorDAO;
        }

        // GET: Fornecedor
        public IActionResult Index()
        {
            return View(_fornecedorDAO.ListarTodos());
        }

        // GET: Fornecedor/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Fornecedor fornecedor)
        {
            if (await _fornecedorDAO.Create(fornecedor))
            {
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "O fornecedor já existe");
            return View();
        }

        public IActionResult Edit(int id)
        {
            Fornecedor fornecedor = _fornecedorDAO.BuscarPorId(id);

            return View(fornecedor);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Fornecedor f)
        {
            _fornecedorDAO.Edit(f);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            _fornecedorDAO.Remover(id);

            return RedirectToAction("Index");
        }
    }
}

BakeryManagement/Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Domain;
using Repository;
using FireSharp.Interfaces;
using FireSharp.Config;
using FireSharp.Response;

namespace BakeryManagement.Controllers
{
    public class ProdutoController : Controller
    {
        private readonly ProdutoDAO _produtoDAO;
        private readonly FornecedorDAO _fornecedorDAO;

        public ProdutoController(ProdutoDAO produto, FornecedorDAO fornecedor)
        {
            _produtoDAO = produto;
            _fornecedorDAO = fornecedor;
        }

        // GET: Produto
        public IActionResult Index()
        {
            return View(_produtoDAO.ListarTodos());
        }

        // GET: Produto/Create
        public IActionResult Create()
        {
            ViewBag.Fornecedores = new SelectList(_fornecedorDAO.ListarTodos(),
                "Id", "Nome");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Produto produto, int drpFornecedor)
        {
            produto.Fornecedor = _fornecedorDAO.BuscarPorId(Convert.ToInt32(drpFornecedor));
            await _produtoDAO.Create(produto);

            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            ViewBag.Fornecedores = new SelectList(_fornecedorDAO.ListarTodos(),
                "Id", "Nome");
            return View(_produtoDAO.BuscarPorId(id));
        }

        [HttpPost]
        public IActionResult Edit(Produto p, int drpFornecedor)
        {
            p.Fornecedor = _fornecedorDAO.BuscarPorId(Convert.ToInt32(drpFornecedor));
            _produtoDAO.Edit(p);

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            _produtoDAO.Remover(id);

            return RedirectToAction("Index");
        }
    }
}

BakeryManagement/Controllers/ProdutoFinalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Domain;
using Repository;
using FireSharp.Interfaces;
using FireSharp.Config;
using FireSharp.Response;

namespace BakeryManagement.Controllers
{
    public class ProdutoFinalController : Controller
    {
        private readonly ProdutoFinalDAO _produtoFinalDAO;
        private readonly ReceitaDAO _receitaDAO;

        public ProdutoFinalController(ProdutoFinalDAO produtoFinalDAO, ReceitaDAO receitaDAO)
        {
            _receitaDAO = receitaDAO;
            _produtoFinalDAO = produtoFinalDAO;
            _receitaDAO = receitaDAO;
        }

        // GET: ProdutoFinal
        public IActionResult Index()
        {

            return View(_produtoFinalDAO.ListarTodos());
        }

        // GET: ProdutoFinal/Create
        public IActionResult Create()
        {
            ViewBag.Receitas = new SelectList(_receitaDAO.ListarTodos(),
                "Id", "Nome");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ProdutoFinal produtoFinal, int drpReceita)
        {
            produtoFinal.Receita = _receitaDAO.BuscarPorId(Convert.ToInt32(drpReceita));
            await _produtoFinalDAO.Create(produtoFinal);

            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            ViewBag.Receitas = new SelectList(_receitaDAO.ListarTodos(),
                "Id", "Nome");
            return View(_produtoFinalDAO.BuscarPorId(id));
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ProdutoFinal pf, int drpReceita)
        {
            pf.Receita = _receitaDAO.BuscarPorId(Convert.ToInt32(drpReceita));
            _produtoFinalDAO.Edit(pf);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            _produtoFinalDAO.Remover(id);

            return RedirectToAction("Index");
        }
    }
}

BakeryManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    @* Barra de naveçação *@
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="~/">Bakery Management</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" asp-action="Index" asp-controller="Categoria">Categoria</a>
                        <a class="dropdown-item" asp-action="Index" asp-controller="Fornecedor">Fornecedor</a>
                        <a class="dropdown-item" asp-action="Index" asp-controller="Receita">Receita</a>
                        <a class="dropdown-item" asp-action="Index" asp-controller="Produto">Produto</a>
                        <a class="dropdown-item" asp-action="Index" asp-controller="ProdutoFinal">Produto Final</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>

    <div class="m-3">
        @RenderBody()
    </div>

    @* Rodapé *@
    <footer>
        <hr />
        <p style="text-align:center">
            &copy; @DateTime.Now.Year
            Desenvolvido por Anderson Guidini, Gabriel Sanches e Tiago Aparecido
        </p>
    </footer>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/js/bootstrap.min.js" integrity="sha384-3qaqj0lc6sV/qpzrc1N5DC6i1VRn/HyX4qdPaiEFbn54VjQBEU341pvjz7Dv3n6P" crossorigin="anonymous"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>